[package]
name = "pocketcache"
version = "0.0.1"
description = "A simple in-memory cache for Rust."
authors = ["shooontan"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
